# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-31 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index_Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(max_length=100)),
                ('num', models.CharField(default='', max_length=20)),
                ('src', models.CharField(default='', max_length=256)),
                ('time', models.CharField(default='', max_length=40)),
                ('describe', models.CharField(default='', max_length=256)),
                ('price', models.CharField(default='', max_length=40)),
                ('salesVolume', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
