# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-05 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_index_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail_json',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='', max_length=8)),
                ('path', models.CharField(default='', max_length=100)),
                ('TV', models.CharField(default='', max_length=20)),
                ('number', models.CharField(default='', max_length=50)),
                ('youHui', models.CharField(default='', max_length=100)),
                ('jiFen', models.CharField(default='', max_length=50)),
                ('smallimg', models.CharField(default='', max_length=256)),
                ('img', models.CharField(default='', max_length=100)),
                ('descibe', models.CharField(default='', max_length=256)),
                ('price', models.DecimalField(decimal_places=2, default='', max_digits=7)),
                ('introduce', models.TextField(default='')),
                ('collocation', models.TextField(default='')),
            ],
        ),
    ]
