# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-10 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='isselect',
            field=models.BooleanField(default=True),
        ),
    ]
